----------------------------------------------------------------------------------------------
--- template from folke/tokyonight.nvim
-----------------------------------------------------------------------------------------------
local colors = require("spacecowboy.colors")

local M = {}

function M.setup(variant)
	local theme = { colors = colors.setup(variant) }
	local c = theme.colors

	theme.highlights = {
		-- UI Elements
		Comment = { fg = c.grey, italic = true },
		ColorColumn = { bg = c.black },
		Conceal = { fg = c.grey },
		Cursor = { fg = c.black, bg = c.muted_orange },
		lCursor = { link = "Cursor" },
		CursorIM = { link = "Cursor" },
		CursorColumn = { bg = c.black },
		CursorLine = { bg = c.black },
		Directory = { fg = c.steel_blue },
		EndOfBuffer = { fg = c.bg },
		ErrorMsg = { fg = c.red, bold = true },
		VertSplit = { fg = c.black },
		Terminal = { bg = c.bg, fg = c.sand },
		WinSeparator = { fg = c.black, bold = false },
		Folded = { fg = c.grey, bg = c.black },
		FoldColumn = { bg = c.none, fg = c.grey },
		SignColumn = { bg = c.none, fg = c.grey },
		SignColumnSB = { bg = c.black, fg = c.grey },
		Substitute = { bg = c.muted_orange, fg = c.black },
		LineNr = { fg = c.grey, bg = c.bg },
		CursorLineNr = { fg = c.muted_orange, bg = c.black, bold = true },
		MatchParen = { fg = c.muted_orange, bg = c.grey, bold = true },
		ModeMsg = { fg = c.desaturated_gold, bold = true },
		MsgArea = { fg = c.sand },
		MoreMsg = { fg = c.steel_blue, bold = true },
		NonText = { fg = c.sand },
		Normal = { fg = c.sand, bg = c.bg },
		NormalNC = { fg = c.sand, bg = c.bg },
		NormalSB = { fg = c.sand, bg = c.black },
		NormalFloat = { fg = c.sand, bg = c.bg },
		FloatBorder = { fg = c.grey, bg = c.bg },
		FloatTitle = { fg = c.muted_orange, bg = c.bg, bold = true },
		Pmenu = { bg = c.bg, fg = c.sand },
		PmenuSel = { bg = c.grey, fg = c.white },
		PmenuSbar = { bg = c.bg },
		PmenuThumb = { bg = c.bg },
		Question = { fg = c.desaturated_gold, bold = true },
		QuickFixLine = { bg = c.black, bold = true },
		Search = { bg = c.muted_orange, fg = c.black },
		IncSearch = { bg = c.muted_orange, fg = c.black },
		CurSearch = { link = "IncSearch" },
		SpecialKey = { fg = c.grey },
		SpellBad = { sp = c.rust, undercurl = true },
		SpellCap = { sp = c.muted_orange, undercurl = true },
		SpellLocal = { sp = c.steel_blue, undercurl = true },
		SpellRare = { sp = c.desaturated_gold, undercurl = true },
		StatusLine = { fg = c.muted_orange, bg = c.black },
		StatusLineNC = { fg = c.grey, bg = c.black },
		TabLine = { bg = c.black, fg = c.grey },
		TabLineFill = { bg = c.black },
		TabLineSel = { fg = c.muted_orange, bg = c.black, bold = true },
		Title = { fg = c.steel_blue, bold = true },
		Visual = { bg = c.grey },
		VisualNOS = { bg = c.grey },
		WarningMsg = { fg = c.muted_orange, bold = true },
		Whitespace = { fg = c.grey },
		WildMenu = { bg = c.black, fg = c.muted_orange },
		WinBar = { link = "StatusLine" },
		WinBarNC = { link = "StatusLineNC" },

		-- Syntax Highlighting (TS/Python focus)
		Identifier = { fg = c.sand },
		Constant = { fg = c.desaturated_gold },
		String = { fg = c.sage_green },
		Character = { fg = c.sage_green },
		Number = { fg = c.warm_yellow },
		Float = { link = "Number" },
		Boolean = { fg = c.warm_yellow },
		Function = { fg = c.steel_blue },
		Keyword = { fg = c.lavender },
		Statement = { fg = c.lavender },
		Conditional = { fg = c.olive },
		Repeat = { fg = c.olive },
		Label = { fg = c.muted_orange },
		Exception = { fg = c.red },
		Operator = { fg = c.grey },
		PreProc = { fg = c.lavender },
		Include = { fg = c.industrial_cyan },
		Define = { fg = c.industrial_cyan },
		Macro = { fg = c.industrial_cyan },
		PreCondit = { fg = c.industrial_cyan },
		Module = { fg = c.industrial_cyan },
		Type = { fg = c.class_teal },
		["@type"] = { link = "Type" },
		["@type.class"] = { fg = c.class_teal },
		["@constructor"] = { fg = c.class_teal },
		Variable = { fg = c.white },
		["@variable"] = { fg = c.white },
		["@variable.parameter"] = { fg = c.desaturated_gold },
		["@variable.member"] = { fg = c.steel_blue },
		["@parameter"] = { fg = c.desaturated_gold },
		["@property"] = { fg = c.muted_orange },
		["@attribute"] = { fg = c.muted_orange },
		["@component"] = { fg = c.class_teal },
		["@namespace"] = { fg = c.industrial_cyan },
		["@module"] = { fg = c.steel_blue },
		StorageClass = { fg = c.steel_blue },
		Structure = { fg = c.lavender },
		Special = { fg = c.sand },
		SpecialChar = { fg = c.sand },
		Tag = { fg = c.coral },
		["@tag.tsx"] = { fg = c.coral },
		["@_jsx_element.tsx"] = { fg = c.coral },
		["@_jsx_attribute.tsx"] = { fg = c.red },
		Delimiter = { fg = c.grey },
		Debug = { fg = c.red, bold = true },
		Underlined = { underline = true },
		Bold = { bold = true },
		Italic = { italic = true },

		["@string.documentation"] = { fg = c.olive, italic = true },
		["@comment.documentation"] = { fg = c.olive },
		["@keyword.return"] = { fg = c.coral },
		["@keyword.operator"] = { fg = c.lavender },
		["@function.builtin"] = { fg = c.steel_blue },
		["@constant.macro"] = { fg = c.noir_purple },
		["@function.macro"] = { fg = c.noir_purple },

		-- LSP
		LspReferenceText = { bg = c.black },
		LspReferenceRead = { bg = c.black },
		LspReferenceWrite = { bg = c.grey, bold = true },
		LspSignatureActiveParameter = { bg = c.black, fg = c.muted_orange, bold = true },
		LspCodeLens = { fg = c.grey },
		LspInlayHint = { bg = c.none, fg = c.sand, italic = true },
		LspInfoBorder = { fg = c.steel_blue, bg = c.black },

		-- Debugging
		debugPC = { bg = c.grey },
		debugBreakpoint = { bg = c.red, fg = c.sand, bold = true },

		-- Diff
		DiffAdd = { bg = c.diff.add_bg, fg = c.grey },
		DiffDelete = { bg = c.diff.delete_bg, fg = c.grey },
		DiffChange = { bg = c.diff.change_bg, fg = c.grey },
		DiffText = { bg = c.diff.change_bg, fg = c.muted_orange, bold = true },

		-- Markdown/Markup
		mkdCodeDelimiter = { bg = c.black, fg = c.muted_orange },
		mkdCodeStart = { fg = c.steel_blue, bold = true },
		mkdCodeEnd = { fg = c.steel_blue, bold = true },
		markdownHeadingDelimiter = { fg = c.steel_blue, bold = true },
		markdownCode = { fg = c.muted_orange },
		markdownCodeBlock = { fg = c.sage_green, bg = c.black },
		markdownH1 = { fg = c.steel_blue, bold = true },
		markdownH2 = { fg = c.desaturated_gold, bold = true },
		markdownLinkText = { fg = c.desaturated_gold, underline = true },
		-- RenderMarkdownCode = { bg = c.black },

		-- Help
		helpCommand = { bg = c.bg, fg = c.muted_orange },
		helpHyperTextJump = { fg = c.desaturated_gold, underline = true },

		-- Quickfix / Location List
		qfLineNr = { fg = c.grey },
		qfFileName = { fg = c.steel_blue },

		-- Health
		healthError = { fg = c.red, bold = true },
		healthSuccess = { fg = c.sage_green, bold = true },
		healthWarning = { fg = c.muted_orange, bold = true },

		-- Flash/Notify/Plugins
		FlashBackdrop = { fg = c.sand, bg = c.bg },
		FlashLabel = { bg = c.red, bold = true, fg = c.black },
		NotifyBackground = { bg = c.bg },
		NotifyERRORBorder = { fg = c.red },
		NotifyWARNBorder = { fg = c.muted_orange },
		NotifyINFOBorder = { fg = c.desaturated_gold },
		NotifyDEBUGBorder = { fg = c.grey },
		NotifyTRACEBorder = { fg = c.grey },
		NotifyERRORTitle = { fg = c.red, bold = true },
		NotifyWARNTitle = { fg = c.muted_orange, bold = true },
		NotifyINFOTitle = { fg = c.desaturated_gold, bold = true },
		NotifyDEBUGTitle = { fg = c.grey, bold = true },
		NotifyTRACETitle = { fg = c.grey, bold = true },

		-- Diagnostics
		Error = { fg = c.red },
		Todo = { bg = c.muted_orange, fg = c.black, bold = true },
		DiagnosticError = { fg = c.red },
		DiagnosticWarn = { fg = c.muted_orange },
		DiagnosticInfo = { fg = c.desaturated_gold },
		DiagnosticHint = { fg = c.sage_green },
		DiagnosticUnnecessary = { fg = c.grey, italic = true },
		DiagnosticVirtualTextError = { bg = c.diagnostic.bg_error, fg = c.red },
		DiagnosticVirtualTextWarn = { bg = c.diagnostic.bg_warn, fg = c.muted_orange },
		DiagnosticVirtualTextInfo = { bg = c.diagnostic.bg_info, fg = c.desaturated_gold },
		DiagnosticVirtualTextHint = { bg = c.diagnostic.bg_hint, fg = c.sage_green },
		DiagnosticUnderlineError = { undercurl = true, sp = c.red },
		DiagnosticUnderlineWarn = { undercurl = true, sp = c.muted_orange },
		DiagnosticUnderlineInfo = { undercurl = true, sp = c.desaturated_gold },
		DiagnosticUnderlineHint = { undercurl = true, sp = c.sage_green },

		SnacksPickerFile = { fg = c.white },
		SnacksPickerDir = { fg = c.grey },

		-- -- Python-specific enhancements
		-- ["@variable.builtin.python"] = { fg = c.white, italic = true },
		-- ["@variable.parameter.python"] = { fg = c.desaturated_gold },
		-- ["@variable.member.python"] = { fg = c.steel_blue },
		-- ["@function.method.python"] = { fg = c.steel_blue },
		-- ["@function.builtin.python"] = { fg = c.sage_green },
		-- ["@property.python"] = { fg = c.muted_orange },
		-- ["@decorator.python"] = { fg = c.noir_purple, bold = true },
		-- ["@type.class.python"] = { fg = c.class_teal, bold = true },
		-- ["@constructor.python"] = { fg = c.class_teal },
		-- ["@string.documentation.python"] = { fg = c.olive, italic = true },
		-- ["@string.interpolation.python"] = { fg = c.desaturated_gold },
		-- ["@punctuation.special.python"] = { fg = c.grey },
		-- ["@constant.builtin.python"] = { fg = c.desaturated_gold, italic = true },
		-- ["@type.builtin.python"] = { fg = c.class_teal },
		-- ["@keyword.function.python"] = { fg = c.lavender },
		-- ["@keyword.return.python"] = { fg = c.coral },
		-- ["@keyword.conditional.python"] = { fg = c.olive },
		-- ["@keyword.repeat.python"] = { fg = c.olive },
		-- ["@keyword.exception.python"] = { fg = c.red },
		-- ["@keyword.import.python"] = { fg = c.lavender },
		--
		-- -- TypeScript/JavaScript-specific enhancements
		-- ["@variable.builtin.javascript"] = { fg = c.white, italic = true },
		-- ["@variable.builtin.typescript"] = { fg = c.white, italic = true },
		-- ["@variable.parameter.javascript"] = { fg = c.desaturated_gold },
		-- ["@variable.parameter.typescript"] = { fg = c.desaturated_gold },
		-- ["@variable.member.javascript"] = { fg = c.steel_blue },
		-- ["@variable.member.typescript"] = { fg = c.steel_blue },
		-- ["@type.class.javascript"] = { fg = c.class_teal, bold = true },
		-- ["@type.class.typescript"] = { fg = c.class_teal, bold = true },
		-- ["@constructor.javascript"] = { fg = c.class_teal },
		-- ["@constructor.typescript"] = { fg = c.class_teal },
		-- ["@function.method.javascript"] = { fg = c.steel_blue },
		-- ["@function.method.typescript"] = { fg = c.steel_blue },
		-- ["@function.builtin.javascript"] = { fg = c.sage_green },
		-- ["@function.builtin.typescript"] = { fg = c.sage_green },
		-- ["@property.javascript"] = { fg = c.muted_orange },
		-- ["@property.typescript"] = { fg = c.muted_orange },
		-- ["@type.annotation.typescript"] = { fg = c.class_teal },
		-- ["@type.parameter.typescript"] = { fg = c.class_teal },
		-- ["@punctuation.bracket.typescript"] = { fg = c.grey },
		-- ["@keyword.type.typescript"] = { fg = c.class_teal },
		-- ["@storageclass.typescript"] = { fg = c.lavender },
		-- ["@keyword.function.javascript"] = { fg = c.lavender },
		-- ["@keyword.function.typescript"] = { fg = c.lavender },
		-- ["@keyword.return.javascript"] = { fg = c.coral },
		-- ["@keyword.return.typescript"] = { fg = c.coral },
		-- ["@constant.builtin.javascript"] = { fg = c.desaturated_gold },
		-- ["@constant.builtin.typescript"] = { fg = c.desaturated_gold },
		-- ["@string.template.javascript"] = { fg = c.sage_green },
		-- ["@string.template.typescript"] = { fg = c.sage_green },
		-- ["@punctuation.special.javascript"] = { fg = c.grey },
		-- ["@punctuation.special.typescript"] = { fg = c.grey },
		-- ["@module.javascript"] = { fg = c.steel_blue },
		-- ["@module.typescript"] = { fg = c.steel_blue },
		--
		-- -- JSX/TSX-specific enhancements
		-- ["@tag.builtin.tsx"] = { fg = c.coral },
		-- ["@tag.builtin.jsx"] = { fg = c.coral },
		-- ["@tag.component.tsx"] = { fg = c.class_teal },
		-- ["@tag.component.jsx"] = { fg = c.class_teal },
		-- ["@tag.attribute.tsx"] = { fg = c.muted_orange },
		-- ["@tag.attribute.jsx"] = { fg = c.muted_orange },
		-- ["@punctuation.bracket.tsx"] = { fg = c.grey },
		-- ["@punctuation.bracket.jsx"] = { fg = c.grey },
		-- ["@keyword.tsx"] = { fg = c.lavender },
		-- ["@keyword.jsx"] = { fg = c.lavender },
		-- ["@string.jsx"] = { fg = c.sage_green },
		-- ["@string.tsx"] = { fg = c.sage_green },
		-- ["@punctuation.delimiter.tsx"] = { fg = c.grey },
		-- ["@punctuation.delimiter.jsx"] = { fg = c.grey },
		--
		-- -- Rust-specific enhancements
		-- ["@variable.parameter.rust"] = { fg = c.desaturated_gold },
		-- ["@variable.member.rust"] = { fg = c.steel_blue },
		-- ["@function.builtin.rust"] = { fg = c.sage_green },
		-- ["@keyword.return.rust"] = { fg = c.coral },
		-- ["@type.class.rust"] = { fg = c.class_teal, bold = true },
		-- ["@function.macro.rust"] = { fg = c.noir_purple },
		-- ["@module.rust"] = { fg = c.steel_blue },
		-- ["@namespace.rust"] = { fg = c.industrial_cyan },
		--
		-- -- Lua-specific enhancements
		-- ["@variable.parameter.lua"] = { fg = c.desaturated_gold },
		-- ["@variable.member.lua"] = { fg = c.steel_blue },
		-- ["@function.builtin.lua"] = { fg = c.sage_green },
		-- ["@keyword.return.lua"] = { fg = c.coral },
		-- ["@constructor.lua"] = { fg = c.class_teal },
		-- ["@module.lua"] = { fg = c.steel_blue },
	}

	return theme
end

return M
